var myString;
var myNum;
var myBool;
var myVar;
//Array of strings
// let strArr: string[];
// let strArr2: string[];
// let numArr: number[];
// let booleanArr: boolean[];
var strArr;
var strArr2;
var numArr;
var booleanArr;
var strNumTuple;
myBool = false;
myNum = 22;
myString = 'Hello'.slice(0, 2);
myVar = true;
strArr = ['Hello', 'World', '1'];
numArr = [1, 2, 3, 4];
booleanArr = [true, false, true, false, false];
console.log(booleanArr[0]);
numArr.forEach(function (num) { return console.log(num); });
strNumTuple = ['Hello', 3];
console.log(strNumTuple);
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myUndefined);
console.log(myNull);
console.log(myVoid);
var strLength = strArr.length;
console.log(strLength);
console.log(myBool);
console.log(myNum);
console.log(myString);
